Tracker: tracker::LAP_JVSparse< FloatT > Class Template Reference
tracker::LAP_JVSparse< FloatT > Class Template Reference
#include </home/travis/build/markjolah/Tracker/include/Tracker/LAP_JVSparse.h>
Static Public Member Functions
static IVecT solve (const SpMatT &C)
static void solveLAP_orig (const SpMatT &C, IVecT &x, IVecT &y, VecT &u, VecT &v)
static VecT computeCost (const SpMatT &C, const IVecT &row_sol)
static bool checkCosts (const SpMatT &C)
static bool checkSolution (const SpMatT &C, const IVecT &x, const IVecT &y, const VecT &u, const VecT &v)
Detailed Description
template<class FloatT>
class tracker::LAP_JVSparse< FloatT >
Definition at line 21 of file LAP_JVSparse.h.
Member Function Documentation
template<class FloatT > bool tracker::LAP_JVSparse< FloatT >::checkCosts (const SpMatT & C) static
Definition at line 95 of file LAP_JVSparse.cpp.
template<class FloatT > bool tracker::LAP_JVSparse< FloatT >::checkSolution (const SpMatT & C, const IVecT & x, const IVecT & y, const VecT & u, const VecT & v) static
Definition at line 118 of file LAP_JVSparse.cpp.
template<class FloatT > LAP_JVSparse< FloatT >::VecT tracker::LAP_JVSparse< FloatT >::computeCost (const SpMatT & C, const IVecT & row_sol) static
Compute the total cost of a solution
Parameters
[in] row_sol This is the 'x' output from the solver giving the col assignment for each row in order
Definition at line 85 of file LAP_JVSparse.cpp.
Referenced by tracker::LAPTrack::debugCloseGaps(), and tracker::LAPTrack::debugF2F().
template<class FloatT > LAP_JVSparse< FloatT >::IVecT tracker::LAP_JVSparse< FloatT >::solve (const SpMatT & C) static
Definition at line 21 of file LAP_JVSparse.cpp.
Referenced by tracker::LAPTrack::closeGaps(), tracker::LAPTrack::debugCloseGaps(), tracker::LAPTrack::debugF2F(), and tracker::LAPTrack::linkF2F().
template<class FloatT > void tracker::LAP_JVSparse< FloatT >::solveLAP_orig (const SpMatT & C, IVecT & x, IVecT & y, VecT & u, VecT & v) static
This wraps the original sparse lap implementation that for some reason uses 1-based indexing, which we correct with some pointer arrithmetic and adjusting of appropriate indicies in the sparse matrix implementation.
Furthermore because the lap_orig code assumes a compressed-row format, but we pass it the internal datastore of a compressed-col format sparse metrix. We invert x/y and u/v on the call to lap_orig to effectively let the transformation work easily with the legacy code.
This means x is the row sol and y is the col sol, as it normally would be.
Parameters
[in] C costs sparse matrix
[out] x - row assignments
[out] y - col assignments
[out] u - reduced row costs
[out] v - reduced column costs
Definition at line 50 of file LAP_JVSparse.cpp.
The documentation for this class was generated from the following files:
LAP_JVSparse.h
LAP_JVSparse.cpp